# Generated by Django 5.0.1 on 2024-02-18 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=64)),
                ('about_scholarship', models.TextField()),
                ('eligibility_scholarship', models.CharField(max_length=64)),
                ('amount_scholarship', models.PositiveIntegerField(default=0)),
                ('lastdate_scholarship', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
