# Generated by Django 5.0.1 on 2024-02-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_scholarships_delete_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='eligibility_scholarship',
            field=models.TextField(),
        ),
    ]
