# Generated by Django 5.0.1 on 2024-03-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_alter_scholarships_eligibility_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('all', 'All')], max_length=10)),
                ('course', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=20)),
                ('Institution', models.CharField(choices=[('kerala', 'Kerala'), ('outside_kerala', 'Outside Kerala')], max_length=20)),
            ],
        ),
    ]
