# Generated by Django 5.0.1 on 2024-03-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.AddField(
            model_name='scholarships',
            name='course',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scholarships',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('all', 'All')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scholarships',
            name='institution',
            field=models.CharField(choices=[('kerala', 'Kerala'), ('outside_kerala', 'Outside Kerala')], max_length=20, null=True),
        ),
    ]
