# Generated by Django 5.0.1 on 2024-03-16 23:35

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_delete_filter_scholarships_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('10th', '10th'), ('12th', '12th'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scholarships',
            name='institution',
            field=models.CharField(choices=[('kerala', 'Kerala'), ('outside_kerala', 'Outside Kerala'), ('all', 'All')], max_length=20, null=True),
        ),
    ]
