# Generated by Django 5.0.1 on 2024-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_alter_scholarships_course_alter_scholarships_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='course',
            field=models.CharField(choices=[('10th', 'Upto 10th'), ('12th', '12th'), ('UG', 'Graduation'), ('PG', 'Postgraduate')], max_length=20),
        ),
    ]
