# Generated by Django 5.0.1 on 2024-03-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_alter_scholarships_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='course',
            field=models.CharField(choices=[('Upto 10th', 'Upto 10th'), ('12th', '12th'), ('Graduation', 'Graduation'), ('Postgraduate', 'Postgraduate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarships',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'Female'), ('all', 'All')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scholarships',
            name='institution',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('outside kerala', 'Outside Kerala'), ('all', 'All')], max_length=20),
        ),
    ]
