# Generated by Django 5.0.1 on 2024-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0010_alter_scholarships_course_alter_scholarships_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], max_length=10),
        ),
    ]
