# Generated by Django 5.0.1 on 2024-03-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0011_alter_scholarships_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
