# Generated by Django 5.0.1 on 2024-03-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0012_alter_scholarships_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='document_required',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
