# Generated by Django 5.0.1 on 2024-03-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0013_scholarships_document_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarships',
            old_name='document_required',
            new_name='documents_required',
        ),
    ]
