# Generated by Django 5.0.1 on 2024-03-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0015_notice_scholarships_notices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarships',
            name='notices',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
