# Generated by Django 5.0.1 on 2024-03-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0016_remove_scholarships_notices_delete_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
